/*
*         OpenPBS (Portable Batch System) v2.3 Software License
*
* Copyright (c) 1999-2000 Veridian Information Solutions, Inc.
* All rights reserved.
*
* ---------------------------------------------------------------------------
* For a license to use or redistribute the OpenPBS software under conditions
* other than those described below, or to purchase support for this software,
* please contact Veridian Systems, PBS Products Department ("Licensor") at:
*
*    www.OpenPBS.org  +1 650 967-4675                  sales@OpenPBS.org
*                        877 902-4PBS (US toll-free)
* ---------------------------------------------------------------------------
*
* This license covers use of the OpenPBS v2.3 software (the "Software") at
* your site or location, and, for certain users, redistribution of the
* Software to other sites and locations.  Use and redistribution of
* OpenPBS v2.3 in source and binary forms, with or without modification,
* are permitted provided that all of the following conditions are met.
* After December 31, 2001, only conditions 3-6 must be met:
*
* 1. Commercial and/or non-commercial use of the Software is permitted
*    provided a current software registration is on file at www.OpenPBS.org.
*    If use of this software contributes to a publication, product, or
*    service, proper attribution must be given; see www.OpenPBS.org/credit.html
*
* 2. Redistribution in any form is only permitted for non-commercial,
*    non-profit purposes.  There can be no charge for the Software or any
*    software incorporating the Software.  Further, there can be no
*    expectation of revenue generated as a consequence of redistributing
*    the Software.
*
* 3. Any Redistribution of source code must retain the above copyright notice
*    and the acknowledgment contained in paragraph 6, this list of conditions
*    and the disclaimer contained in paragraph 7.
*
* 4. Any Redistribution in binary form must reproduce the above copyright
*    notice and the acknowledgment contained in paragraph 6, this list of
*    conditions and the disclaimer contained in paragraph 7 in the
*    documentation and/or other materials provided with the distribution.
*
* 5. Redistributions in any form must be accompanied by information on how to
*    obtain complete source code for the OpenPBS software and any
*    modifications and/or additions to the OpenPBS software.  The source code
*    must either be included in the distribution or be available for no more
*    than the cost of distribution plus a nominal fee, and all modifications
*    and additions to the Software must be freely redistributable by any party
*    (including Licensor) without restriction.
*
* 6. All advertising materials mentioning features or use of the Software must
*    display the following acknowledgment:
*
*     "This product includes software developed by NASA Ames Research Center,
*     Lawrence Livermore National Laboratory, and Veridian Information
*     Solutions, Inc.
*     Visit www.OpenPBS.org for OpenPBS software support,
*     products, and information."
*
* 7. DISCLAIMER OF WARRANTY
*
* THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT
* ARE EXPRESSLY DISCLAIMED.
*
* IN NO EVENT SHALL VERIDIAN CORPORATION, ITS AFFILIATED COMPANIES, OR THE
* U.S. GOVERNMENT OR ANY OF ITS AGENCIES BE LIABLE FOR ANY DIRECT OR INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
* OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
* NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
* This license will be governed by the laws of the Commonwealth of Virginia,
* without reference to its choice of law rules.
*/
/*
 * queue_recov.c - This file contains the functions to record a queue
 * data struture to disk and to recover it from disk.
 *
 * The data is recorded in a file whose name is the queue name
 *
 * The following public functions are provided:
 *  que_save()  - save the disk image
 *  que_recov()  - recover (read) queue from disk
 */

#include <pbs_config.h>   /* the master config generated by configure */
#include "queue_recov.h"

#include <sys/types.h>
#include <sys/param.h>
#include "pbs_ifl.h"
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "server_limits.h"
#include "list_link.h"
#include "attribute.h"
#include "queue.h"
#include "svrfunc.h"
#include "log.h"
#include "../lib/Liblog/pbs_log.h"
#include "../lib/Liblog/log_event.h"
#include "lib_ifl.h"
#include "utils.h"
#include <pthread.h>
#include "queue_func.h" /* que_alloc, que_free */
#include <libxml/tree.h>

/* data global to this file */

extern char   *path_queues;

/* parseResourcesValue
 * 
 * takes a xmlNodePtr to store the resource values in
 * and a string which is the values of the resource_default attribute
 *
 * content should look similar to this
 * "\t\t<walltime>300</walltime>\n\t\t<nodes>1</nodes>\n"
 * for any number of resource_defaults 
 *
 * called by que_save_attr_xml
*/
void parseResourcesValue(
    
  xmlNodePtr  &res_defaults,
  std::string  content)

  {
  
  while(content != "")
    {
          
    int find_less = content.find("<");
    content = content.substr(find_less+1);
    
    int find_greater = content.find(">");
    std::string name = content.substr(0,find_greater);
    
    content = content.substr(name.size()+1);
    
    find_less = content.find("<");
    std::string value = content.substr(0,find_less);
    
    int find_close = content.find(name);
    content = content.substr(find_close+name.size());
    if (content.find("<") == std::string::npos)
      {
      content = "";
      }
   
    xmlNewChild(res_defaults, NULL, BAD_CAST name.c_str(),BAD_CAST value.c_str());

     }
  }



/* que_save_attr_xml
 * 
 * stores the que attributes into a libxml2 NodePtr
 * which is used in que_save() to write out to disk
 *
*/
int que_save_attr_xml(
 
  struct attribute_def *padef,   /* pbs_attribute definition array */
  pbs_attribute        *pattr,   /* ptr to pbs_attribute value array */
  int                   numattr, /* number of attributes in array */
  xmlNodePtr            node_tree)    /* xml node attributes to fill*/  
  {
  int             i;
  int             rc = PBSE_NONE;
  char            log_buf[LOCAL_LOG_BUF_SIZE];
  std::string     attr_string = "";


  xmlNodePtr node = NULL;
  for (node = node_tree->xmlChildrenNode; node != NULL;node = node->next)
    {
    if(!xmlStrcmp(node->name, BAD_CAST "attributes"))
      {
      break;
      }
    }

  if (node == NULL)
    return(-1);

  for (i = 0; i < numattr; i++)
    {
    if (pattr[i].at_flags & ATR_VFLAG_SET)
      {
      attr_string.clear();

      if ((rc = attr_to_str(attr_string, padef+i, pattr[i], true)) != 0)
        {
        if (rc != NO_ATTR_DATA)
          {
          /* ERROR */
          snprintf(log_buf,sizeof(log_buf),
              "Not enough space to print pbs_attribute %s",
              padef[i].at_name);

          return(rc);
          }
        }
      else
        {
        if (padef[i].at_type == ATR_TYPE_RESC)
          {
          xmlNewChild(node,NULL,BAD_CAST padef[i].at_name,NULL);
          xmlNodePtr res_defaults = node->last;
          parseResourcesValue(res_defaults,attr_string);
          }
        else if (attr_string == "" )
          {
          xmlNewChild(node, NULL, BAD_CAST padef[i].at_name, BAD_CAST "0");
          }
        else
          {
          xmlNewChild(node, NULL, BAD_CAST padef[i].at_name, BAD_CAST attr_string.c_str());
          }
        }
      }
    } /* END for each pbs_attribute */

  /* we can just return this since its the last write */
  return(rc);
  } /* END que_save_attr_xml() */



/*
 * que_save() - Saves a queue structure image on disk
 *
 *
 * For a save, to ensure no data is ever lost due to system crash:
 * 1. write new image to a new file using a temp name
 * 2. rename the new file over the old one
 *
 * Then, if the queue has any access control lists, they are saved
 * to their own files.
 */

int que_save(

  pbs_queue *pque)

  {
  int fds;
  int rc;
  char namebuf1[MAXPATHLEN];
  char namebuf2[MAXPATHLEN];
  char node_value[MAXLINE];

  xmlDocPtr doc = NULL;
  doc = xmlNewDoc(BAD_CAST "1.0");
  

  pque->qu_attr[QA_ATR_MTime].at_val.at_long = time(NULL);
  pque->qu_attr[QA_ATR_MTime].at_flags = ATR_VFLAG_SET;

  snprintf(namebuf1,sizeof(namebuf1),
    "%s%s",
    path_queues,
    pque->qu_qs.qu_name);
  snprintf(namebuf2,sizeof(namebuf2),"%s.new",namebuf1);

  fds = open(namebuf2, O_CREAT | O_WRONLY | O_Sync, 0600);

  if (fds < 0)
    {
    log_err(errno, __func__, (char *)"open error");

    return(-1);
    }

  xmlNodePtr root_node = xmlNewNode(NULL, BAD_CAST "queue");
  xmlDocSetRootElement(doc, root_node);
  xmlNodePtr node = root_node;
  
  snprintf(node_value, sizeof(node_value),"%i",pque->qu_qs.qu_modified);
  xmlNewChild(node, NULL, BAD_CAST "modified", BAD_CAST node_value);
  
  snprintf(node_value, sizeof(node_value),"%i",pque->qu_qs.qu_type);
  xmlNewChild(node, NULL, BAD_CAST "type", BAD_CAST node_value);

  snprintf(node_value, sizeof(node_value),"%ld",pque->qu_qs.qu_ctime);
  xmlNewChild(node, NULL, BAD_CAST "create_time", BAD_CAST node_value);

  snprintf(node_value, sizeof(node_value),"%ld",pque->qu_qs.qu_mtime);
  xmlNewChild(node, NULL, BAD_CAST "modify_time", BAD_CAST node_value);
  xmlNewChild(node, NULL, BAD_CAST "name", BAD_CAST pque->qu_qs.qu_name);
  xmlNewChild(node, NULL, BAD_CAST "attributes", NULL);

  if (que_save_attr_xml(que_attr_def, pque->qu_attr, QA_ATR_LAST,root_node) != 0)
    {
    log_err(-1, __func__, (char *)"que_save_attr failed");
    close(fds);
    return(-1);
    }

  xmlBuffer *xml_buffer = xmlBufferCreate();
  xmlOutputBuffer *outputBuffer = xmlOutputBufferCreateBuffer( xml_buffer, NULL );
  xmlSaveFormatFileTo( outputBuffer, doc, "utf-8", 1 );
  std::string xml_out_str( (char*) xml_buffer->content, xml_buffer->use );
  
  if ((rc = write_buffer(xml_out_str.c_str(), xml_out_str.size(), fds)))
    {
    log_err(rc, __func__, (char *)"unable to write to the queue's file");
    close(fds);
    return(-1);
    }

  /* Close the file descriptor and check for errors */
  if (close(fds) < 0)
    {
    log_err(errno, __func__, (char *)"unable to close the queue's file");
    return(-1);
    }

  if (rename(namebuf2, namebuf1) < 0)
    {
    log_err(errno, __func__, (char *)"unable to replace queue file");
    return(-1);
    }

  return(0);
  } /* END que_save_xml() */





pbs_queue *que_recov_xml(

  char *filename)

  {
  int          rc;
  pbs_queue   *pq;
  char         namebuf[MAXPATHLEN];
  char         buf[MAXLINE<<10];
  char         log_buf[LOCAL_LOG_BUF_SIZE];
  time_t       time_now = time(NULL);

  memset(&buf, 0, sizeof(buf));

  pq = que_alloc(filename, TRUE);  /* allocate & init queue structure space */

  if (pq == NULL)
    {
    log_err(-1, __func__, "que_alloc failed");

    return(NULL);
    }

  snprintf(namebuf, sizeof(namebuf), "%s%s", path_queues, filename);


  xmlDocPtr doc = NULL;
  doc = xmlReadFile(namebuf,NULL,0);
  /* read in queue save sub-structure */
  if(doc == NULL)
    {
    snprintf(log_buf,sizeof(log_buf),
      "Unable to read from queue file %s",
      filename);
    log_err(errno, __func__, log_buf);
       
    que_free(pq, TRUE);

    return(NULL);
    }

  xmlNodePtr root_node = xmlDocGetRootElement(doc);
  std::string que_node((char*)root_node->name);
  if (que_node != "queue")
    {
    log_event(PBSEVENT_SYSTEM,
      PBS_EVENTCLASS_SERVER,
      __func__,
      "Cannot find a queue tag, attempting to load legacy format");
    que_free(pq, TRUE);

    return(que_recov(filename));
    }
  
  for (xmlNodePtr current_node = root_node->xmlChildrenNode;
       current_node != NULL;
       current_node = current_node->next)
    {
    std::string parent(((char*)current_node->name));
    if (parent != "text")//check for filler nodes
      {
      xmlChar *content = xmlNodeGetContent(current_node);
      std::string child(((char*)content));
        
      if (parent == "modified")
        pq->qu_qs.qu_modified = atoi(child.c_str());
      else if (parent =="type")
        pq->qu_qs.qu_type = atoi(child.c_str());
      else if (parent == "create_time")
        pq->qu_qs.qu_ctime = atoi(child.c_str());
      else if (parent == "modify_time")
        pq->qu_qs.qu_mtime = atoi(child.c_str());
      else if (parent == "name")
        snprintf(pq->qu_qs.qu_name,sizeof(pq->qu_qs.qu_name),"%s",child.c_str());
      else if (parent == "attributes")
        {
        for (xmlNodePtr attr_children = current_node->xmlChildrenNode;
             attr_children != NULL;
             attr_children = attr_children->next)
          {
          std::string attr_parent((char *)attr_children->name);
          if (attr_parent != "text")//skipe node if it is a filler node
            {
            xmlChar *attr_content = xmlNodeGetContent(attr_children);
            char *attr_child = (char *)attr_content;

            if ((attr_parent == ATTR_rescdflt) ||
                (attr_parent == ATTR_rescassn) || 
                (attr_parent == ATTR_rescmax) || 
                (attr_parent == ATTR_rescavail) || 
                (attr_parent == ATTR_rescmin)) //see if the child is a rescource
              {
              for (xmlNodePtr res_child_node = attr_children->xmlChildrenNode;
                   res_child_node != NULL;
                   res_child_node = res_child_node->next)
                {
                std::string res_parent = ((char*)res_child_node->name);
                if (res_parent != "text")
                  {
                  xmlChar *res_child_content = xmlNodeGetContent(res_child_node);
                  std::string res_child((char*)res_child_content);
                  xmlFree(res_child_content);

                  // Format the resource child look like this <walltime>100</walltime>
                  // for str_to_attr()
                  res_parent.insert(0,"<");
                  res_parent.insert(res_parent.end(),'>');
                  res_child.insert(0,res_parent);
                  res_parent.insert(1,"/");
                  res_child.insert(res_child.end(),res_parent.begin(),res_parent.end());

                  if ((rc = str_to_attr(attr_parent.c_str(), res_child.c_str(),
                          pq->qu_attr,que_attr_def,QA_ATR_LAST)))
                    {
                    /* ERROR */
                    snprintf(log_buf,sizeof(log_buf),
                        "Error creating resource attribute %s",
                        attr_parent.c_str());
                    log_err(rc, __func__, log_buf);
                    
                    que_free(pq, TRUE);

                    xmlFree(attr_content);
                    xmlFree(content);
                    return(NULL);
                    }
                  }

                }    
              }    
                       
            else if ((rc = str_to_attr(attr_parent.c_str(),attr_child,pq->qu_attr,que_attr_def,QA_ATR_LAST)))
              {
              /* ERROR */
              snprintf(log_buf,sizeof(log_buf),
                "Error creating attribute %s",
                attr_parent.c_str());
              log_err(rc, __func__, log_buf);

              que_free(pq, TRUE);

              xmlFree(attr_content);
              xmlFree(content);
              return(NULL);
              }

            xmlFree(attr_content);
            }
          }
        }

      xmlFree(content);
      }
    } 

  /* all done recovering the queue */
  xmlFreeDoc(doc);

  if ((pq->qu_attr[QA_ATR_MTime].at_flags & ATR_VFLAG_SET) == 0)
    {
    /* if we are recovering a pre-2.1.2 queue, save a new mtime */

    pq->qu_attr[QA_ATR_MTime].at_val.at_long = time_now;
    pq->qu_attr[QA_ATR_MTime].at_flags = ATR_VFLAG_SET;

    que_save(pq);
    }

  return(pq);
  } /* END que_recov_xml() */





/*
 * que_recov() - load (recover) a queue from its save file
 *
 * This function is only needed upon server start up.
 *
 * The queue structure is recovered from the disk.
 * Space to hold the above is calloc-ed as needed.
 *
 * Returns: pointer to new queue structure if successful
 *   null if error
 */

pbs_queue *que_recov(

  char *filename) /* pathname to queue save file */

  {
  int        fds;
  int        i;
  pbs_queue *pq;
  char       namebuf[MAXPATHLEN];
  time_t     time_now = time(NULL);

  pq = que_alloc(filename, TRUE);  /* allocate & init queue structure space */

  if (pq == NULL)
    {
    log_err(-1, __func__, "que_alloc failed");

    return(NULL);
    }

  snprintf(namebuf, sizeof(namebuf), "%s%s", path_queues, filename);

  fds = open(namebuf, O_RDONLY, 0);

  if (fds < 0)
    {
    log_err(errno, __func__, "open error");

    que_free(pq, TRUE);

    return(NULL);
    }

  /* read in queue save sub-structure */

  if (read_ac_socket(fds, (char *)&pq->qu_qs, sizeof(queuefix)) !=
      sizeof(queuefix))
    {
    log_err(errno, __func__, "read error");
    que_free(pq, TRUE);
    close(fds);
    return ((pbs_queue *)0);
    }

  /* read in queue attributes */

  if (recov_attr(fds, pq, que_attr_def, pq->qu_attr,
	               QA_ATR_LAST, 0, TRUE) != 0)
    {
    log_err(-1, __func__, "recov_attr[common] failed");
    que_free(pq, TRUE);
    close(fds);
    return ((pbs_queue *)0);
    }

  /*
   * now reload the access control lists, these attributes were
   * saved separately
   */

  for (i = 0;i < QA_ATR_LAST;i++)
    {
    if (pq->qu_attr[i].at_type == ATR_TYPE_ACL)
      {
      recov_acl(
        &pq->qu_attr[i],
        &que_attr_def[i],
        que_attr_def[i].at_name,
        pq->qu_qs.qu_name);
      }
    }

  /* all done recovering the queue */

  close(fds);

  if ((pq->qu_attr[QA_ATR_MTime].at_flags & ATR_VFLAG_SET) == 0)
    {
    /* if we are recovering a pre-2.1.2 queue, save a new mtime */

    pq->qu_attr[QA_ATR_MTime].at_val.at_long = time_now;
    pq->qu_attr[QA_ATR_MTime].at_flags = ATR_VFLAG_SET;

    que_save(pq);
    }

  return(pq);
  }
