#include <pbs_config.h>   /* the master config generated by configure */

#include <sys/types.h>
#include <stdio.h>
#include <signal.h>
#include "libpbs.h"
#include "server_limits.h"
#include "list_link.h"
#include "work_task.h"
#include "attribute.h"
#include "server.h"
#include "credential.h"
#include "batch_request.h"
#include "job.h"
#include "queue.h"
#include "pbs_error.h"
#include "acct.h"
#include "log.h"
#include "svrfunc.h"

void req_deletearray(struct batch_request *preq)
  {
  	
  req_reject(PBSE_INTERNAL,0,preq,"whole array deletion not yet implemented",NULL);
  /* reply_ack(preq); */

  return;
  }
