#! /bin/sh

###       AddPrivileges  ver 1.0     19 Nov 2009           ###
### ------------------------------------------------------ ###
###  This script creates Passwd&Group files and sets       ###
###   additional privileges only for Windows users         ###
###    with Computer administrator privileges.             ###
###  It must be run at the first Torque pbs_server         ###
###   and Torque pbs_mom installation on Cygwin.           ###


OS=`uname -s | tr '[A-Z]' '[a-z]'`

case $OS in
   cygwin*) ;;
   *) echo "   Script can run on Cygwin 1.5 only"
      exit 1;;
esac


case $1 in
  '')
     echo "   No user's login.  Try \`$0 --help' for more information."
     exit 1;
     ;;
  -h | --h*)
    cat <<\EOF

Usage: AddPrivileges [--help] [--version] UserAdmin [mom]

 Set additional privileges for Windows (Cygwin) user

 Run from user with Computer administrator privileges only

 Options:
   --help, -h      display this help and exit
   --version, -v   output version information and exit

   UserAdmin       login of Windows user
                    with Computer administrator privileges or
		   SYSTEM - native Windows user
		    
   mom             add privileges for Torque pbs_mom only

EOF
    exit $?
    ;;
  -v | --v*)
    echo
    echo " AddPrivileges  ver 1.0    19 Nov 2009"
    exit $?
    ;;
esac


CURRENTU=`whoami`

PASSWDF=/etc/passwd

GROUPF=/etc/group

ADMINGR=544:544


mkpasswd -l > $PASSWDF

mkgroup -l -u > $GROUPF

chmod 644 $PASSWDF

chmod 644 $GROUPF


if grep "$ADMINGR" "$GROUPF" | grep -q "$CURRENTU";

    then echo;

    else echo "   Current user '$CURRENTU' has not administrator privileges"
    exit $?;
fi


if [ "$1" = "SYSTEM" ]; then

    echo
    echo "   Passwd&Group files were created"
    echo
    exit $?;

fi


if grep "$ADMINGR" "$GROUPF" | grep -q $1;

    then echo "   $1 has got Computer administrator privileges";

    else echo "   $1 is not Windows user with Computer administrator privileges"
    exit $?;
fi


if [ "$2" = "mom" ]; then 

    editrights -a SeCreateTokenPrivilege -u $1

fi


editrights -a SeServiceLogonRight -u $1


if [[ $? -eq $SUCCESS ]]; then

 cat <<\EOF

   Passwd&Group files and additional privileges were set successfully

   Should run 'editrights -l -u UserAdmin'
    to ascertain of the privileges installation

 Warning!!! You have to understand that the installing of additional privileges
            can decrease your OS security level

EOF
fi


