#!/bin/sh
#
# pbs_server	This script will start and stop the PBS Server
#
# chkconfig: 345 95 5
# description: PBS is a versatile batch system for SMPs and clusters
#
# Source the library functions
. /etc/rc.d/init.d/functions

PBS_DAEMON=/usr/sbin/pbs_server
PBS_HOME=/usr/spool/PBS
export PBS_DAEMON PBS_HOME

if [ -f /etc/sysconfig/pbs_server ];then
   . /etc/sysconfig/pbs_server
fi

# let see how we were called
case "$1" in
	start) 
		echo -n "Starting TORQUE Server: "
		if [ -r $PBS_HOME/server_priv/serverdb ]
		then
			daemon $PBS_DAEMON
		else
			daemon $PBS_DAEMON -t create
		fi
		RET=$?
		touch /var/lock/subsys/pbs_server
		echo
		;;
	stop)
		echo -n "Shutting down TORQUE Server: "
		killproc pbs_server
		RET=$?
		rm -f /var/lock/subsys/pbs_server
		echo
		;;
	status)
		status pbs_server
		RET=$?
		;;
	restart)
		$0 stop
		$0 start
		;;
	reload)
		echo -n "Reloading pbs_server: "
		killproc pbs_server -HUP
		RET=$?
		echo
		;;
	*)
		echo "Usage: pbs_server {start|stop|restart|status|reload}"
		exit 1
esac
exit $RET
