PROG_ROOT = ../..

AM_CFLAGS = -g -DTEST_FUNCTION -I${PROG_ROOT}/ -I${PROG_ROOT}/${PBS_MACH} --coverage `xml2-config --cflags`

lib_LTLIBRARIES = libuut.la libscaffolding.la

AM_LDFLAGS = @CHECK_LIBS@ ${lib_LTLIBRARIES}

check_PROGRAMS = test_uut

libuut_la_LDFLAGS = @CHECK_LIBS@
libscaffolding_la_SOURCES = scaffolding.c
libscaffolding_la_LDFLAGS = @CHECK_LIBS@
test_uut_LDADD = ./.libs/libuut.la ./.libs/libscaffolding.la ../.libs/libscaffolding_svr.la ../../../test/torque_test_lib/libtorque_test.la ./.libs/libscaffolding.la ../../../test/scaffold_fail/libscaffold_fail.la

test_uut_SOURCES = test_uut.c 

check_SCRIPTS = coverage_run.sh

TESTS = ${check_PROGRAMS} coverage_run.sh

CLEANFILES = coverage_run.sh *.gcno *.gcda *.gcov core *.lo
